'use client';
import {useState} from 'react';
type Sel={eventId:string;event:string;league:string;kickoff:string;selection:string;bookmaker:string;odds:number;impliedProbability:number;modelProbability:number;edge:number};
type Acca={legs:Sel[];combinedOdds:number;combinedScore:number};
type Result={ok:boolean;error?:string;scannedSports?:number;events?:number;selections?:Sel[];twoLeg?:Acca[];threeLeg?:Acca[];generatedAt?:string};
const pct=(v:number)=>`${(v*100).toFixed(1)}%`; const dt=(v:string)=>new Date(v).toLocaleString();
function SelectionCard({s}:{s:Sel}){return <div className="card"><div className="row"><span className="pill">{s.league}</span><span className="value">{s.odds.toFixed(2)}</span></div><h3>{s.selection}</h3><div>{s.event}</div><small>{dt(s.kickoff)} · Best price: {s.bookmaker}</small><div className="grid" style={{marginTop:12}}><div><small>Market implied</small><div>{pct(s.impliedProbability)}</div></div><div><small>Model</small><div>{pct(s.modelProbability)}</div></div><div><small>Edge</small><div className={s.edge>0?'positive':'negative'}>{pct(s.edge)}</div></div></div></div>}
function AccaCard({a}:{a:Acca}){return <div className="card"><div className="row"><b>{a.legs.length}-leg acca</b><span className="value">{a.combinedOdds.toFixed(2)}</span></div><div className="legs">{a.legs.map((l,i)=><div className="leg" key={l.eventId+'-'+i}><b>{l.selection}</b> @ {l.odds.toFixed(2)}<div><small>{l.event}</small></div></div>)}</div></div>}
export default function Home(){const [loading,setLoading]=useState(false); const [r,setR]=useState<Result|null>(null); async function scan(){setLoading(true); try{const x=await fetch('/api/scan'); setR(await x.json());}catch(e){setR({ok:false,error:'Could not reach the scanner'});}finally{setLoading(false);}} return <main><div className="hero"><div><h1>Betsite V2</h1><div className="muted">Global football value scanner · market-derived consensus model</div></div><button onClick={scan} disabled={loading}>{loading?'Scanning…':'SCAN NOW'}</button></div><div className="card"><div className="row"><div><b>Target odds</b><div className="muted">1.90–2.10 centred on 2.00</div></div><div className="pill">Server-side API key</div></div></div>{r&&!r.ok&&<div className="section"><div className="empty"><b>Scanner unavailable</b><div className="muted">{r.error}</div></div></div>}{r&&r.ok&&<><div className="section"><div className="grid"><div className="card"><small>Sports scanned</small><div className="value">{r.scannedSports}</div></div><div className="card"><small>Events</small><div className="value">{r.events}</div></div><div className="card"><small>Qualifying selections</small><div className="value">{r.selections?.length??0}</div></div></div></div><section className="section"><h2>Best value selections</h2>{r.selections?.length?<div className="grid">{r.selections.map(s=><SelectionCard key={s.eventId+'-'+s.selection} s={s}/>)}</div>:<div className="empty"><b>NO BET</b><div className="muted">No selections currently meet the configured value and odds thresholds.</div></div>}</section><section className="section"><h2>2-leg accumulators</h2>{r.twoLeg?.length?<div className="grid">{r.twoLeg.map((a,i)=><AccaCard key={i} a={a}/>)}</div>:<div className="empty"><b>NO BET</b></div>}</section><section className="section"><h2>3-leg accumulators</h2>{r.threeLeg?.length?<div className="grid">{r.threeLeg.map((a,i)=><AccaCard key={i} a={a}/>)}</div>:<div className="empty"><b>NO BET</b></div>}</section><div className="section"><small>Generated {r.generatedAt&&dt(r.generatedAt)} · Model probability is market-derived in V2 and is not an independently trained prediction.</small></div></>}</main>}
